### ISSUE TITLE
Coordinates are uploaded to Wikimedia in a wrong format.

### ISSUE THREAD

**Issue by surveyor54** [trougnouf/dtMediaWiki#8]
Hello,
I used the plugin for the first time and I am excited.
Unfortunately I have the following problem. When I upload a photo, which has coordinates in the exif, to Wikimedia, I get an error message that the coordinate format is wrong.
This is the format in which the coordinates are uploaded to Wikimedia: **{{location |1=50,264978018889 |2=10,076506733889 }}**.
If I replace the commas with dots, the coordinate format is correct.

Greetings
surveyor54

**Comment by trougnouf** [comment]
Thank you for reporting :) I think it's fixed in 7c2a2c79e96c4ef3838eb6127ff4576996d9e337 . Can you check that it's working, or otherwise share a picture with its sidecar file?

**Comment by surveyor54** [comment]
It's working, thank you for the fast fixing.  :+1:
